version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: flight_mysql
    environment:
      MYSQL_ROOT_PASSWORD: Vasudha**23
      MYSQL_DATABASE: flight
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./filght-booking-backend/FLIGHT_BOOKING
    container_name: flight_backend
    ports:
      - "8900:8900"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/flight?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Vasudha**23
    depends_on:
      - mysql

  frontend:
    build: ./filght-booking-frontend
    container_name: flight_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql_data: